import type {
  MaterialDefinition,
  MaterialId,
  MaterialPhysics,
  Vec3,
} from "./contracts.js";

const DEFAULT_PHYSICS = {
  friction: 0.55,
  restitution: 0.15,
  linearDamping: 0.08,
  angularDamping: 0.12,
  dragCoefficient: 1.05,
  cushioning: 0,
  buoyancyFactor: 0,
  breakForceN: 160,
} as const satisfies Omit<MaterialPhysics, "densityKgM3">;

function material(
  definition: Omit<MaterialDefinition, "physics"> & {
    physics: Pick<MaterialPhysics, "densityKgM3"> & Partial<MaterialPhysics>;
  },
): MaterialDefinition {
  return {
    ...definition,
    defaultDimensions: [...definition.defaultDimensions] as Vec3,
    physics: { ...DEFAULT_PHYSICS, ...definition.physics },
  };
}

export const MATERIAL_CATALOG = [
  material({
    id: "straw",
    label: "Straws",
    description: "Lightweight tubes for frames, cages, and outriggers.",
    category: "structure",
    behaviors: ["rigid"],
    geometry: "rod",
    cost: 1,
    color: "#ef476f",
    defaultDimensions: [0.012, 0.3, 0.012],
    physics: { densityKgM3: 95, breakForceN: 38 },
  }),
  material({
    id: "tape",
    label: "Tape",
    description: "A strong fixed connector between two pieces.",
    category: "connector",
    behaviors: ["flexible", "fixedJoint"],
    geometry: "strip",
    cost: 1,
    color: "#e8d7a5",
    defaultDimensions: [0.025, 0.12, 0.002],
    physics: { densityKgM3: 910, friction: 0.8, breakForceN: 120 },
  }),
  material({
    id: "glue",
    label: "Glue",
    description: "Bonds two pieces rigidly at any spot you click.",
    category: "connector",
    behaviors: ["flexible", "fixedJoint"],
    geometry: "strip",
    cost: 2,
    color: "#f1efe3",
    defaultDimensions: [0.02, 0.02, 0.02],
    physics: { densityKgM3: 1100, friction: 0.9, breakForceN: 150 },
  }),
  material({
    id: "balloon",
    label: "Balloons",
    description: "Helium-filled lift with a large amount of aerodynamic drag.",
    category: "aerodynamic",
    behaviors: ["flexible", "drag", "buoyant"],
    geometry: "sphere",
    cost: 5,
    color: "#7b61ff",
    defaultDimensions: [0.3, 0.38, 0.3],
    physics: {
      // Effective helium + latex mass per inflated volume; lower than air so
      // displaced-air buoyancy produces real lift in the simulation.
      densityKgM3: 0.55,
      // Latex is grippy and absorbs load; low friction + high restitution made
      // loaded balloons squirt out sideways like marbles instead of cushioning.
      friction: 0.9,
      restitution: 0.35,
      linearDamping: 0.3,
      dragCoefficient: 0.47,
      cushioning: 0.2,
      buoyancyFactor: 0.92,
      breakForceN: 12,
    },
  }),
  material({
    id: "bubbleWrap",
    label: "Bubble wrap",
    description: "Low-mass impact padding that spreads a sharp collision.",
    category: "cushion",
    behaviors: ["flexible", "cushion"],
    geometry: "sheet",
    cost: 4,
    color: "#b9edf8",
    defaultDimensions: [0.25, 0.03, 0.25],
    physics: {
      densityKgM3: 32,
      restitution: 0.08,
      linearDamping: 0.28,
      cushioning: 0.72,
      breakForceN: 48,
    },
  }),
  material({
    id: "string",
    label: "String",
    description: "A flexible tether for hanging parts or making a parachute harness.",
    category: "connector",
    behaviors: ["flexible", "ropeJoint"],
    geometry: "rope",
    cost: 1,
    color: "#f2e8cf",
    defaultDimensions: [0.004, 0.35, 0.004],
    physics: { densityKgM3: 720, dragCoefficient: 1.2, breakForceN: 75 },
  }),
  material({
    id: "cardboard",
    label: "Cardboard",
    description: "Broad structural panels that are sturdy but add weight.",
    category: "structure",
    behaviors: ["rigid", "drag"],
    geometry: "sheet",
    cost: 3,
    color: "#b98552",
    defaultDimensions: [0.3, 0.012, 0.22],
    physics: { densityKgM3: 690, friction: 0.7, dragCoefficient: 1.28, breakForceN: 210 },
  }),
  material({
    id: "craftStick",
    label: "Craft sticks",
    description: "Dense wooden beams for a stiff protective frame.",
    category: "structure",
    behaviors: ["rigid"],
    geometry: "rod",
    cost: 2,
    color: "#d9a066",
    defaultDimensions: [0.018, 0.15, 0.004],
    physics: { densityKgM3: 620, friction: 0.62, breakForceN: 260 },
  }),
  material({
    id: "paperCup",
    label: "Paper cups",
    description: "A light shell that can cradle an egg or form a crush zone.",
    category: "structure",
    behaviors: ["rigid", "cushion", "drag"],
    geometry: "cup",
    cost: 3,
    color: "#faf3dd",
    defaultDimensions: [0.09, 0.11, 0.09],
    physics: { densityKgM3: 280, restitution: 0.1, cushioning: 0.28, breakForceN: 42 },
  }),
  material({
    id: "cottonBall",
    label: "Cotton balls",
    description: "Soft, light padding for the egg's immediate surroundings.",
    category: "cushion",
    behaviors: ["flexible", "cushion"],
    geometry: "puff",
    cost: 1,
    color: "#fffdf7",
    defaultDimensions: [0.06, 0.06, 0.06],
    physics: {
      densityKgM3: 18,
      restitution: 0.02,
      linearDamping: 0.4,
      cushioning: 0.82,
      breakForceN: 18,
    },
  }),
  material({
    id: "foamBlock",
    label: "Foam blocks",
    description: "Thick, low-density blocks for corners and impact zones.",
    category: "cushion",
    behaviors: ["cushion"],
    geometry: "box",
    cost: 4,
    color: "#ffd166",
    defaultDimensions: [0.12, 0.12, 0.12],
    physics: {
      densityKgM3: 45,
      friction: 0.8,
      restitution: 0.05,
      linearDamping: 0.32,
      cushioning: 0.9,
      breakForceN: 32,
    },
  }),
  material({
    id: "sponge",
    label: "Sponges",
    description: "Springy padding that compresses and rebounds on impact.",
    category: "cushion",
    behaviors: ["flexible", "cushion"],
    geometry: "box",
    cost: 4,
    color: "#f4d35e",
    defaultDimensions: [0.12, 0.06, 0.08],
    physics: {
      densityKgM3: 80,
      friction: 0.85,
      restitution: 0.22,
      linearDamping: 0.35,
      cushioning: 0.78,
      breakForceN: 55,
    },
  }),
  material({
    id: "rubberBand",
    label: "Rubber bands",
    description: "Elastic suspension joints that stretch under sudden loads.",
    category: "connector",
    behaviors: ["flexible", "springJoint"],
    geometry: "rope",
    cost: 2,
    color: "#d1495b",
    defaultDimensions: [0.004, 0.12, 0.004],
    physics: { densityKgM3: 920, restitution: 0.65, breakForceN: 42 },
  }),
  material({
    id: "newspaper",
    label: "Newspaper",
    description: "A crumplable sheet for drag, wrapping, or a crush zone.",
    category: "cushion",
    behaviors: ["flexible", "cushion", "drag"],
    geometry: "sheet",
    cost: 2,
    color: "#d9d9d9",
    defaultDimensions: [0.3, 0.008, 0.25],
    physics: {
      densityKgM3: 120,
      dragCoefficient: 1.25,
      cushioning: 0.5,
      breakForceN: 22,
    },
  }),
  material({
    id: "plasticBag",
    label: "Plastic bags",
    description: "A very light sheet with enough area to become a parachute.",
    category: "aerodynamic",
    behaviors: ["flexible", "drag"],
    geometry: "bag",
    cost: 4,
    color: "#cae9ff",
    defaultDimensions: [0.45, 0.012, 0.45],
    physics: {
      densityKgM3: 24,
      linearDamping: 0.45,
      dragCoefficient: 1.42,
      breakForceN: 16,
    },
  }),
  material({
    id: "packingPeanuts",
    label: "Packing peanuts",
    description: "Tiny foam pieces that make a light, compressible buffer.",
    category: "cushion",
    behaviors: ["cushion"],
    geometry: "cluster",
    cost: 1,
    color: "#f7fff7",
    defaultDimensions: [0.08, 0.05, 0.04],
    physics: {
      densityKgM3: 12,
      restitution: 0.06,
      linearDamping: 0.38,
      cushioning: 0.86,
      breakForceN: 10,
    },
  }),
  material({
    id: "fishingWeight",
    label: "Fishing weights",
    description: "A dense lead sinker that adds ballast exactly where you need it.",
    category: "structure",
    behaviors: ["rigid"],
    geometry: "box",
    cost: 2,
    color: "#5f6b76",
    defaultDimensions: [0.015, 0.025, 0.015],
    physics: {
      densityKgM3: 11340,
      friction: 0.4,
      restitution: 0.05,
      dragCoefficient: 0.45,
      breakForceN: 900,
    },
  }),
] as const satisfies readonly MaterialDefinition[];

export const MATERIAL_BY_ID: Readonly<Record<MaterialId, MaterialDefinition>> =
  Object.freeze(
    Object.fromEntries(MATERIAL_CATALOG.map((item) => [item.id, item])) as Record<
      MaterialId,
      MaterialDefinition
    >,
  );

export function getMaterial(materialId: MaterialId): MaterialDefinition {
  return MATERIAL_BY_ID[materialId];
}
